__author__ = 'mep'

DATE = 'Date'           # Date, this is fixed to format yy/mm/dd for easier sorting
HOME_TEAM = 'HomeTeam'
AWAY_TEAM = 'AwayTeam'
REFEREE = 'Referee'     # Referee name
ATTENDANCE = 'ATTENDANCE'
FTR = 'FTR'             # Full-time result
FTHG = 'FTHG'           # Full-time home goals
FTAG = 'FTAG'           # Full-time away goals
HE = 'HE'               # Home ELO rating before match
HEC = 'HEC'             # Home ELO rating change from before
AE = 'AE'               # Away ELO rating before match
AEC = 'AEC'             # Away ELO rating change from before
HS = 'HS'               # Home team shots
AS = 'AS'               # Away team shots
HST = 'HST'             # Home team shots on target
AST = 'AST'             # Away team shots on target
HC = 'HC'               # Home team corners
AC = 'AC'               # Away team corners
HHW = 'HHW'             # Home team hit woodwork
AHW = 'AHW'             # Away team hit woodwork
HF = 'HF'               # Home team fouls commited
AF = 'AF'               # Away team fouls commited
HO = 'HO'               # Home team offsides
AO = 'AO'               # Away team offsides
HY = 'HY'               # Home team yellow cards
AY = 'AY'               # Away team yellow cards
HR = 'HR'               # Home team red cards
AR = 'AR'               # Away team red cards
